name: Test

on: [push]


jobs:
  debug:
    name: Debug
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Pandoc
        run: |
          curl -L -O https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-linux.tar.gz
          sudo tar xvzf ./pandoc-2.7.3-linux.tar.gz --strip-components 1 -C /usr/local/bin
          pandoc --help

      - name: Debug
        run: echo $RUNNER_TEMP $RUNNER_TOOL_CACHE $PATH;
