name: Test

on: [push]


jobs:
  debug:
    name: Debug
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Get Pandoc
        run: curl -L -O https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-linux.tar.gz
      - name: Install Pandoc
        run: sudo tar xvzf ./pandoc-2.7.3-linux.tar.gz --strip-components 1 -C /usr/local/
      - name: Debug
        run: pandoc --help
      - name: Environment
        run: printenv
