name: Test

on: [push]


jobs:
  debug:
    name: Debug
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]
    steps:
      - uses: mgred/pandoc-action@master
      - name: Pandoc
        run: pandoc --help
